### ISSUE TITLE
random error 500 on webclient 

### ISSUE THREAD

**Issue by si458** [Devolutions/WaykDen-ps#105]
500 Internal Server Error POST https://remote.mefoo.com/wayk/message
`{"type":"/wayk/problems/internal-server-error","title":"Internal server error","status":500,"detail":"An error happened during the process. Please see server logs for more information."}`

only errors i can find on the den-server is below

```
2020-07-06T17:44:01.632058735+00:00 INFO den_server::http::middlewares::log - POST /wayk/message 500 Internal Server Error (Den-Version=3, User-Agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:78.0) Gecko/20100101 Firefox/78.0, Client-Ip=217.14.xxx.xxx, 172.18.0.2),
2020-07-06T17:44:01.631961547+00:00 ERROR den_server::http::error_code - cow call failed: Internal error: timed out
```

**Comment by fdubois1** [comment]
Hi Simon,

The reason of the error seems to be a timeout to reach the WaykNow Server. Of course, we should probably handle that error in a better way to inform the user that we are not able to reach the server instead of showing a 500 Internal Server Error. We already have a ticket on our side to improve error messages so I will add that specific case.

But I would like to understand more why you get this error randomly.  Except if the network signal is bad or in some edge cases, it should work. What is the WaykNow server (OS, WaykNow version) ?  Could you send me the WaykNow server logs ? I could look to see if the server received the request or if the server didn't answer that request. We could understand why we got a timeout. If your WaykNow server that you are trying to open a session on it is Windows, there is a menu `Help > Export Diagnostics` that will create a zip file with all logs. Otherwise, if the WaykNow server is  linux with unattended, the NowService.log is in /etc/wayk/logs/NowService.log. And if your server is a macOs, client and server log are in the same file, WaykNow.log.

And if you could describe the operation that you do to get the error, it could be useful. Do you open the Web Client and type the Target ID ? Or you click on the server you want to connect to in the server list and click WebClient ?  

Thank you
