### ISSUE TITLE
Windows 10 not compatible?

### ISSUE THREAD

**Issue by damianlavalle** [Devolutions/WaykDen-ps#92]
Wow, so this installation is anything but easy. None the less, I managed to make my way though it and finally arrived at the point to where I "Start-Waykden" and this is what I get.

PS C:\ProgramData\Devolutions\Wayk Den> Start-WaykDen
docker pull library/mongo:4.2-windowsservercore-1809
no matching manifest for windows/amd64 10.0.17134 in the manifest list entries
docker pull devolutions/picky:4.2.1-servercore-ltsc2019
a Windows version 10.0.17763-based image is incompatible with a 10.0.17134 host
docker pull devolutions/den-lucid:3.6.6-servercore-ltsc2019
a Windows version 10.0.17763-based image is incompatible with a 10.0.17134 host
docker pull devolutions/den-server:1.18.0-servercore-ltsc2019
a Windows version 10.0.17763-based image is incompatible with a 10.0.17134 host
docker pull library/traefik:1.7-windowsservercore-1809
no matching manifest for windows/amd64 10.0.17134 in the manifest list entries
Starting den-mongo
Unable to find image 'mongo:4.2-windowsservercore-1809' locally
4.2-windowsservercore-1809: Pulling from library/mongo
C:\Program Files\Docker\Docker\resources\bin\docker.exe: no matching manifest for windows/amd64 10.0.17134 in the manifest list entries.
See 'C:\Program Files\Docker\Docker\resources\bin\docker.exe run --help'.
Error: No such object: den-mongo
Error starting den-mongo
At C:\Program Files\WindowsPowerShell\Modules\WaykDen\2020.1.8\Public\WaykDenService.ps1:543 char:9
+         throw "Error starting $($Service.ContainerName)"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error starting den-mongo:String) [], RuntimeException
    + FullyQualifiedErrorId : Error starting den-mongo

**Comment by awakecoding** [comment]
Hi! I would recommend using Windows Server 2019 or Ubuntu 18.04 LTS as your base OS instead of Windows 10 for Wayk Den. Windows 10 should work, but there a more things you need to be careful, as Docker Desktop for Windows is quite different from the Docker you find on Windows Server.

First, make sure you have switched to Windows containers in Docker Desktop:
https://stackoverflow.com/questions/48066994/docker-no-matching-manifest-for-windows-amd64-in-the-manifest-list-entries

Then try again. There exists a --platform=windows option that forces the platform for the containers, but this option requires that you enable experimental features in Docker, so we can't inject it by default without breaking things. This is why you need to globally switch to Windows containers in Docker desktop.

**Comment by My1** [comment]
apparently the error messages relate to the specific windows you are running.

a Windows version 10.0.17763-based image is incompatible with a 10.0.17134 host
this means your windows (the host) is running 1803 but the image asks for 1809.

also as a sidenote. you need w10 pro instead of home to get any luck with docker because hyperv.
